version: '3.8'

services:
  app:
    image: 'app:latest'
    container_name: app
    build:
      context: .
      args:
        - ENV=${ENV}
        - PROJECT_DIR=${PROJECT_DIR}
        - SRC_DIR=${SRC_DIR}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:${PROJECT_DIR}${SRC_DIR}
      - ./logs:${LOG_PATH}
    depends_on:
      - db
    networks:
      - app_network
    command: ${PROJECT_DIR}/start_reload.sh
    env_file:
      - ./.env

  db:
    container_name: app_db
    image: postgres:14-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - app_network
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  app_network:

volumes:
  app_postgres_data:
